execute:
  freeze: auto 
  
project: 
  type: website
  output-dir: docs

website: 
  title: "Raquel P. Romasanta"   
  search: true  
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: posts.qmd
        text: News
      - text: Resources
        menu:
          - text: Descriptive Statistics
            file: descriptive.qmd
          - text: Inferential Statistics
            file: inferential.qmd
          - text: R Code Library
            file: rcode.qmd
      - href: contact.qmd
        text: Contact 

          



format: 
  html:
    theme: flatly
